detect_relations: true

Project:
    tableName: projects
    actAs:
        Timestampable:
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        name:
            type: string
            length: 255
            notnull: true
        name_jp:
            type: string
            length: 255
        description:
            type: string
            length: 60000
        poster:
            type: string
            length: 255
        mini_poster:
            type: string
            length: 255
        status:
            type: enum
            values: ['planned','progress','pending','completed','dropped','licensed']
            notnull: true
        private:
            type: enum
            values: ['yes','no']
            default: 'yes'
            notnull: true
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

ProjectUser:
    tableName: project_users
    columns:
        user_id:
            type: integer
            primary: true
            notnull: true
        project_id:
            type: integer
            primary: true
            notnull: true
        function:
            type: string
            length: 255
    relations:
        User:
            onDelete: CASCADE
            onUpdate: CASCADE
        Project:
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

ProjectLeader:
    tableName: project_leaders
    columns:
        user_id:
            type: integer
            primary: true
            notnull: true
        project_id:
            type: integer
            primary: true
            notnull: true
    relations:
        User:
            onDelete: CASCADE
            onUpdate: CASCADE
        Project:
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
        type: InnoDB
        collate: utf8_unicode_ci
        charset: utf8

ProjectScreenshot:
    tableName: project_screenshots
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        project_id:
            type: integer
            notnull: true
        screenshot:
            type: string
            length: 255
            unique: true
            notnull: true
    relations:
        Project:
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

ProjectTask:
    tableName: project_task_types
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        name:
            type: string
            length: 128
        description:
            type: string
            length: 255
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

ProjectUserTask:
    tableName: project_tasks
    columns:
        project_episode_id:
            type: integer
            primary: true
            notnull: true
        user_id:
            type: integer
            primary: true
            notnull: true
        project_task_id:
            type: integer
            primary: true
            notnull: true
    relations:
        ProjectEpisode:
            onDelete: CASCADE
            onUpdate: CASCADE
        User:
            onDelete: CASCADE
            onUpdate: CASCADE
        ProjectTask:
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

ProjectEpisode:
    tableName: project_episodes
    actAs: [Timestampable]
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        project_id:
            type: integer
            notnull: true
        number:
            type: integer
            length: 4
        version:
            type: integer
            length: 2
        vcodec:
            type: string
            length: 10
        acodec:
            type: string
            length: 10
        container:
            type: string
            length: 10
        crc:
            type: string
            length: 8
        title:
            type: string
            length: 255
        updated_by:
            type: string
            length: 32
        released_at:
            type: timestamp
    relations:
        Project:
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8