Projects_Model_Project:
    tableName: projects
    actAs:
        Timestampable:
        Sluggable:
            name: name_slug
            unique: true
            fields: [name]
            canUpdate: true
            type: string
            length: 255
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        name:
            type: string
            length: 255
            notnull: true
        name_jp:
            type: string
            length: 255
        description:
            type: string
            length: 60000
        poster:
            type: string
            length: 255
        mini_poster:
            type: string
            length: 255
        status:
            type: enum
            values: ['planned','progress','pending','completed','dropped','licensed']
            notnull: true
        element_count:
            type: integer
        project_type:
            type: enum
            values: ['fansub','scanlation']
            default: 'fansub'
            notnull: true
        private:
            type: enum
            values: ['yes','no']
            default: 'yes'
            notnull: true
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

Projects_Model_User:
    tableName: project_users
    columns:
        user_id:
            type: integer
            primary: true
            notnull: true
        project_id:
            type: integer
            primary: true
            notnull: true
        function:
            type: string
            length: 255
    relations:
        User_Model_User:
            local: user_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
        Projects_Model_Project:
            local: project_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

Projects_Model_Leader:
    tableName: project_leaders
    columns:
        user_id:
            type: integer
            primary: true
            notnull: true
        project_id:
            type: integer
            primary: true
            notnull: true
    relations:
        User_Model_User:
            local: user_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
        Projects_Model_Project:
            local: project_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
        type: InnoDB
        collate: utf8_unicode_ci
        charset: utf8
        
Projects_Model_TaskType:
    tableName: project_task_types
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        project_id:
            type: integer
        title:
            type: string
            length: 255
        description:
            type: string
            length: 60000
    relations:
        Projects_Model_Project:
            local: project_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

Projects_Model_Task:
    tableName: project_tasks
    actAs: [Timestampable]
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        task_id:
            type: integer
        user_id:
            type: integer
        chapter_id:
            type: integer
        episode_id:
            type: integer
        done:
            type: integer
            length: 3
        comment:
            type: string
            length: 60000
    relations:
        Projects_Model_TaskType:
            local: task_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
        User_Model_User:
            local: user_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
        Projects_Model_Episode:
            local: episode_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
        Projects_Model_Chapter:
            local: chapter_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8

Projects_Model_Screenshot:
    tableName: project_screenshots
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        project_id:
            type: integer
            notnull: true
        screenshot:
            type: string
            length: 255
            unique: true
            notnull: true
        description:
            type: string
            length: 6000
    relations:
        Projects_Model_Project:
            local: project_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8
       
Projects_Model_Episode:
    tableName: project_episodes
    actAs: [Timestampable]
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        project_id:
            type: integer
            notnull: true
        number:
            type: integer
            length: 4
        version:
            type: integer
            length: 2
        title:
            type: string
            length: 255        
    relations:
        Projects_Model_Project:
            local: project_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8
       
Projects_Model_EpisodeRelease:
    tableName: project_episode_releases
    actAs: [Timestampable]
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        episode_id:
            type: integer
        vcodec:
            type: string
            length: 10
        acodec:
            type: string
            length: 10
        container:
            type: string
            length: 10
        crc:
            type: string
            length: 8
        released_at:
            type: timestamp
        updated_by:
            type: string
            length: 32
    relations:
        Projects_Model_Episode:
            local: episode_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8
            
Projects_Model_Chapter:
    tableName: project_chapters
    actAs: [Timestampable]
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        project_id:
            type: integer
            notnull: true
        number:
            type: integer
            length: 5
        version:
            type: integer
            length: 2
    relations:
        Projects_Model_Project:
            local: project_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8
       
Projects_Model_ChapterRelease:
    tableName: project_chapter_releases
    actAs: [Timestampable]
    columns:
        id:
            type: integer
            primary: true
            autoincrement: true
            notnull: true
        chapter_id:
            type: integer
        format:
            type: string
            length: 10
        resolution:
            type: string
            length: 10
        title:
            type: string
            length: 255
        updated_by:
            type: string
            length: 32
        released_at:
            type: timestamp
    relations:
        Projects_Model_Chapter:
            local: chapter_id
            foreign: id
            type: one
            onDelete: CASCADE
            onUpdate: CASCADE
    options:
       type: InnoDB
       collate: utf8_unicode_ci
       charset: utf8